Eng 1083 update auto refresh
ORIGYN-SA/DApps pull request #78
Opened 2023-01-23 12:13 UTC by aletex1994

• Refactored NFTLibrary and Collection Library, after library update data is automatically refreshed.
• Small fixes to the layout ( progress bar was not showed in Collection Update, Web Update)

2023-01-24 16:12 UTC, Motokoder commented
Please save all your file with prettier, then I will review. Thanks.

2023-01-26 15:10 UTC, Motokoder requested changes
Comments are not resolved.

2023-01-27 09:35 UTC, aletex1994 commented on packages/apps/library/src/components/CollectionLibrary/index.tsx
> +  const [objLibraryData, setObjLibraryData] = React.useState<SimplifiedMeta>({
objLibraryData --> simplifiedLibraryMeta

2023-01-27 09:52 UTC, aletex1994 commented on packages/apps/library/src/components/CollectionLibrary/index.tsx
> +    const metadata = await props.library3;
Deleted await

2023-01-27 11:53 UTC, aletex1994 commented on packages/apps/library/src/components/CollectionLibrary/index.tsx
> +    if (metadata.Class.filter((item) => item.name === 'com.origyn.immutable_library')[0]) {
Done, created a folder constants > constants.ts

2023-01-27 14:33 UTC, Motokoder approved these changes

2023-01-27 14:33 UTC, merged